# Generated by Django 5.2.14 on 2026-05-07 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of applicant', max_length=255)),
                ('date_of_birth', models.DateField(help_text="Applicant's date of birth (DD/MM/YYYY)")),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender of applicant', max_length=20)),
                ('nationality', models.CharField(help_text="Applicant's nationality", max_length=100)),
                ('previous_school', models.CharField(help_text='Previous basic school attended', max_length=255)),
                ('class_completed', models.CharField(help_text='Class completed (e.g., JHS 3, Primary 6)', max_length=50)),
                ('bece_index_number', models.CharField(help_text='BECE Index Number', max_length=50)),
                ('bece_year', models.IntegerField(help_text='Year BECE was taken')),
                ('aggregate_score', models.CharField(help_text='Aggregate score from BECE', max_length=50)),
                ('subjects_and_grades', models.TextField(help_text='Subjects and grades (English, Math, Science, Social Studies, Others)')),
                ('program_applied_for', models.CharField(help_text='Program applied for (General Science, Business, etc.)', max_length=100)),
                ('accommodation_status', models.CharField(choices=[('Boarding', 'Boarding'), ('Day', 'Day')], help_text='Boarding or Day student', max_length=20)),
                ('parent_name', models.CharField(help_text='Full name of parent/guardian', max_length=255)),
                ('parent_relationship', models.CharField(help_text='Relationship to applicant (Parent, Guardian, etc.)', max_length=50)),
                ('parent_occupation', models.CharField(help_text="Parent/guardian's occupation", max_length=100)),
                ('parent_contact', models.CharField(help_text="Parent/guardian's contact number(s)", max_length=20)),
                ('parent_address', models.TextField(help_text='Residential address of parent/guardian')),
                ('parent_email', models.EmailField(help_text='Email address of parent/guardian', max_length=254)),
                ('alumni_name', models.CharField(help_text='Full name of PRESEC Old Boy', max_length=255)),
                ('alumni_year_group', models.CharField(help_text="Alumni's year group (e.g., 1998, 2005)", max_length=4)),
                ('alumni_class_stream', models.CharField(help_text="Alumni's class stream (e.g., Science 2, Business 1)", max_length=100)),
                ('alumni_house', models.CharField(help_text="Alumni's house at PRESEC", max_length=100)),
                ('alumni_phone', models.CharField(help_text="Alumni's phone number", max_length=20)),
                ('alumni_email', models.EmailField(help_text="Alumni's email address", max_length=254)),
                ('alumni_occupation', models.CharField(help_text="Alumni's current occupation/title", max_length=100)),
                ('alumni_organization', models.CharField(help_text="Alumni's current organization/institution", max_length=255)),
                ('alumni_relationship', models.CharField(help_text="Alumni's relationship to applicant", max_length=100)),
                ('reason_for_recommendation', models.TextField(help_text='Reason for recommendation by alumnus')),
                ('bece_results', models.FileField(help_text='Copy of BECE Results Slip', upload_to='attachments/bece_results/')),
                ('passport_photo', models.ImageField(help_text='Passport photograph', upload_to='attachments/passport_photos/')),
                ('birth_certificate', models.FileField(help_text='Birth certificate', upload_to='attachments/birth_certificates/')),
                ('medical_form', models.FileField(blank=True, help_text='Medical form (optional)', null=True, upload_to='attachments/medical_forms/')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, help_text='Date and time when the record was submitted')),
                ('submitted_by', models.ForeignKey(help_text='User who submitted this admission record', on_delete=django.db.models.deletion.CASCADE, related_name='admission_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Record',
                'verbose_name_plural': 'Admission Records',
                'ordering': ['-date_submitted'],
                'indexes': [models.Index(fields=['submitted_by', '-date_submitted'], name='admissions__submitt_34eeb9_idx'), models.Index(fields=['full_name'], name='admissions__full_na_de4607_idx')],
            },
        ),
    ]
