# Generated by Django 5.2.14 on 2026-05-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrecord',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete - Awaiting BECE Results'), ('complete', 'Complete - Ready for Review')], default='incomplete', help_text='Application completion status', max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='bece_results',
            field=models.FileField(blank=True, help_text='Copy of BECE Results Slip', null=True, upload_to='attachments/bece_results/'),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male')], help_text='Gender of applicant', max_length=20),
        ),
    ]
