# Generated by Django 5.2.14 on 2026-05-26 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionrecord_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrecord',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the record was validated', null=True),
        ),
        migrations.AddField(
            model_name='admissionrecord',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='President or admin who validated this admission record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_admission_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissionrecord',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Notes from the validator, especially when revision is needed'),
        ),
        migrations.AddField(
            model_name='admissionrecord',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending President Validation'), ('approved', 'Approved'), ('rejected', 'Needs Revision')], default='pending', help_text='Year group president validation status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='admissionrecord',
            index=models.Index(fields=['alumni_year_group', 'validation_status'], name='admissions__alumni__7bf67f_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionrecord',
            index=models.Index(fields=['validation_status', '-date_submitted'], name='admissions__validat_9dde23_idx'),
        ),
    ]
