# Generated by Django 5.2.14 on 2026-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissionrecord_validated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrecord',
            name='alumni_house',
            field=models.CharField(choices=[('House 1', 'House 1'), ('House 2', 'House 2'), ('House 3', 'House 3'), ('House 4', 'House 4'), ('House 5', 'House 5'), ('House 6', 'House 6'), ('House 7', 'House 7'), ('House 8', 'House 8'), ('House 9', 'House 9'), ('House 10', 'House 10'), ('House 11', 'House 11'), ('House 12', 'House 12'), ('House 13', 'House 13')], help_text="Alumni's house at PRESEC", max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='alumni_relationship',
            field=models.CharField(choices=[('Son', 'Son'), ('Nephew', 'Nephew'), ('Grandson', 'Grandson'), ('Other', 'Other')], help_text="Alumni's relationship to applicant", max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='alumni_year_group',
            field=models.CharField(choices=[('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('1993_shs', '1993_shs'), ('1993_olevel', '1993_olevel'), ('1994_shs', '1994_shs'), ('1994_olevel', '1994_olevel')], help_text="Alumni's year group (e.g., 1998, 2005, 1993_shs)", max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='parent_relationship',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Guardian', 'Guardian')], help_text='Relationship to applicant (Parent, Guardian, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='program_applied_for',
            field=models.CharField(choices=[('General Arts', 'General Arts'), ('Visual Arts', 'Visual Arts'), ('Business', 'Business'), ('General Science', 'General Science')], help_text='Program applied for (General Science, Business, etc.)', max_length=100),
        ),
    ]
