# Generated by Django 5.2.14 on 2026-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year_group',
            field=models.CharField(blank=True, help_text='Year group (e.g., 1998, 2005, 2015, 1993_shs, 1993_olevel)', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'president')), fields=('year_group', 'role'), name='unique_president_per_year_group'),
        ),
    ]
