# Generated by Django 5.2.14 on 2026-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_year_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('president', 'Year Group President'), ('individual', 'Individual')], default='president', help_text='User role in the system', max_length=20),
        ),
    ]
