# Generated by Django 5.2.14 on 2026-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year_group',
            field=models.CharField(blank=True, help_text='Year group (e.g., 1998, 2005, 2015, 1993_shs, 1993_olevel)', max_length=20),
        ),
    ]
